const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const hashtags = [
    '#programming',
    '#technology',
    '#coding',
    '#development',
    '#webdevelopment',
    '#software',
    '#codinglife',
    '#developer',
    '#codingcommunity',
    '#webdev',
    '#tech',
    '#javascript',
    '#codingisfun',
    '#code',
    '#programmer',
    '#codinglove',
    '#html',
    '#css',
    '#python',
    '#java',
    '#cplusplus',
    '#php',
    '#ruby',
    '#gamedev',
    '#datascience',
    '#artificialintelligence',
    '#machinelearning',
    '#datascientist',
    '#data',
    '#iot',
    '#cloud',
    '#cybersecurity',
    '#blockchain',
    '#startup',
    '#entrepreneur',
    '#business',
    '#finance',
    '#investing',
    '#money',
    '#marketing',
    '#socialmedia',
    '#digitalmarketing',
    '#contentmarketing',
    '#branding',
    '#influencer',
    '#photography',
    '#travel',
    '#food',
    '#fashion',
    '#fitness',
    '#health',
    '#lifestyle',
    '#music',
    '#art',
    '#film',
    '#books',
    '#writing',
    '#quotes',
    '#motivation',
    '#inspiration',
    '#love',
    '#family',
    '#friends',
    '#selfie',
    '#instagood',
    '#photooftheday',
    '#picoftheday',
    '#happy',
    '#fun',
    '#beautiful',
    '#nature',
    '#sun',
    '#sunset',
    '#sky',
    '#clouds',
    '#beach',
    '#mountains',
    '#landscape',
    '#architecture',
    '#city',
    '#urban',
    '#night',
    '#stars',
    '#moon',
    '#travelphotography',
    '#foodie',
    '#yum',
    '#delicious',
    '#fashionista',
    '#style',
    '#ootd',
    '#workout',
    '#fitspo',
    '#healthy',
    '#instafit',
    '#wellness',
    '#yoga',
    '#meditation'
];

const createHashtags = async function (hashtags) {
    try {
        const newHashtags = await prisma.tag.createMany({
            data: hashtags.map(tag => ({ name: tag })),
            skipDuplicates: true
        });
        console.log(newHashtags);
        return newHashtags;
    } catch (error) {
        console.error(error);
    }
};

createHashtags(hashtags);
